window.LV_COPY = {
  no: {
    'meta.title': 'Los Verdiales — Marbella',
    'meta.description': 'Los Verdiales — en privat residens i Marbella.',
    'nav.residence': 'Residensen',
    'nav.interiors': 'Interiør',
    'nav.wellness': 'Velvære',
    'nav.plans': 'Planer',
    'nav.contact': 'Visning',
    'nav.menu': 'Meny',
    'nav.close': 'Lukk',
    'hero.aria': 'Kjøkken og stue',
    'hero.location': 'Marbella · Spania',
    'hero.tagline': 'Et stille hus mellom stein, lys og hage.',
    'hero.cta.plans': 'Se plantegninger',
    'hero.cta.viewing': 'Be om visning',
    'hero.alt': 'Åpent kjøkken og stue med gardiner i brisen ved glassdørene',
    'opening.kicker': 'Residensen',
    'opening.headline': 'Noe man kjenner<br>før man forstår.',
    'opening.p1': 'Los Verdiales er tenkt som én helhet — arkitektur, interiør og landskap i samme bevegelse. Rommene åpner seg mot hagen. Stein, eik, messing og lin gir varme og varighet.',
    'opening.p2': 'Luksusen ligger i proporsjonene, håndverket og dagslyset. Huset er rolig med vilje.',
    'facts.place.label': 'Sted',
    'facts.residence.label': 'Residens',
    'facts.wellness.label': 'Velvære',
    'facts.plan.label': 'Plan',
    'kitchen.kicker': 'Kjøkken og stue',
    'kitchen.headline': 'Huset åpner seg her.',
    'kitchen.body': 'Kjøkkenøya, stuen og hagen i én flukt. Salvie lanterner, eik og stein — rommet dagen samles i.',
    'kitchen.alt': 'Åpent kjøkken og stue med salvie lanterner, sofa og glass mot hagen',
    'bedroom.kicker': 'Hovedsoverommet',
    'bedroom.headline': 'Et mykere tempo.',
    'bedroom.body': 'Hvit wingback, lag på lag med tekstiler og dempede lamper. Et rom som føles bebodd — ikke stylet.',
    'bedroom.alt': 'Hovedsoverom med hvit wingback og dempede lamper',
    'bathroom.kicker': 'Bad',
    'bathroom.headline': 'Salvie, messing, ro.',
    'bathroom.body': 'Frittstående badekar i dempet salvie. Riflet servant i varm messing. Jord og mineral — rolig, taktilt, uten hast.',
    'bathroom.alt': 'Bad med salvie badekar og riflet messing servant',
    'lounge.kicker': 'Fritid',
    'lounge.headline': 'Kvelder uten slutt.',
    'lounge.body': 'Bar, vinvegg, biljard og avslappet sittegruppe. Et eget rom på nedre plan — fortsatt i samme materialfortelling.',
    'lounge.alt': 'Lounge med bar, biljard og vinvegg',
    'poolgym.kicker': 'Velvære',
    'poolgym.headline': 'Et tilfluktssted i huset.',
    'poolgym.body': 'Basseng, treningsrom og spa bak glass — vann, lys og restitusjon.',
    'poolgym.alt': 'Innendørs basseng og treningsrom bak glass',
    'pool.aria': 'Basseng og kveld',
    'pool.kicker': 'Ute · Kveld',
    'pool.headline': 'Kveldsro ved bassenget.',
    'pool.body': 'Villaen i skumring. Turkis basseng, lounge og chevron-parasoller — kvelden faller over hagen.',
    'dusk.kicker': 'Skumring',
    'dusk.headline': 'Huset samler lyset.',
    'dusk.body': 'Fra kjøkkenøya åpner stuen seg mot terrassen og peisen. Dagen legger seg i varme.',
    'dusk.alt': 'Stue i skumring sett fra kjøkkenøya mot terrasse og peis',
    'place.kicker': 'Marbella',
    'place.headline': 'Ro uten å være langt unna.',
    'place.p1': 'Los Verdiales ligger i et rolig hjørne av Marbella — nær kysten, men skjermet av hage og stein. Dagen kan være stille her; kvelden samler lyset innover.',
    'place.p2': 'Huset er tenkt for dem som vil ha nærhet til Middelhavet uten å bo i støy. Ingen brochure — bare et sted som puster rolig.',
    'exterior.kicker': 'Eksteriør',
    'exterior.headline': 'Huset i landskapet.',
    'plans.kicker': 'Privat materiale',
    'plans.headline': 'Plantegninger',
    'plans.gate.body': 'Plantegninger deles med dem som vurderer en privat visning. Legg inn e-post for å åpne.',
    'plans.form.name': 'Navn (valgfritt)',
    'plans.form.email': 'E-post',
    'plans.form.submit': 'Åpne plantegninger',
    'plans.form.error': 'Noe gikk galt. Prøv igjen, eller be om visning under.',
    'plans.empty': 'Plantegning lastes inn',
    'plans.tab.hovedplan': 'Hovedplan',
    'plans.tab.underetasje': 'Underetasje',
    'plans.tab.situasjon': 'Situasjon',
    'plans.caption.hovedplan': 'Kjøkken, stue og hovedsoverom',
    'plans.caption.underetasje': 'Lounge, basseng og treningsrom',
    'plans.caption.situasjon': 'Huset i hagen',
    'plans.download': 'Last ned PDF',
    'plans.lightbox.close': 'Lukk',
    'contact.kicker': 'Privat presentasjon',
    'contact.headline': 'Los Verdiales<br>Marbella',
    'contact.body': 'For spesifikasjoner, planer og privat visning — be om full presentasjon.',
    'contact.plansNote': 'Plantegninger åpnes med e-post under <a href="#plans">Planer</a>.',
    'form.name': 'Navn',
    'form.email': 'E-post',
    'form.phone': 'Telefon',
    'form.message': 'Melding',
    'form.submit': 'Be om presentasjon',
    'footer.brand': 'Los Verdiales · Marbella · Spania',
    'footer.plans': 'Plantegninger',
    'footer.contact': 'Visning',
    'footer.location': 'Marbella · Spania',
    'thanks.title': 'Takk — Los Verdiales',
    'thanks.headline': 'Takk for henvendelsen.',
    'thanks.body': 'Vi tar kontakt snart med detaljer om privat presentasjon og visning.',
    'thanks.back': 'Tilbake til residensen'
  },
  en: {
    'meta.title': 'Los Verdiales — Marbella',
    'meta.description': 'Los Verdiales — a private residence in Marbella.',
    'nav.residence': 'The residence',
    'nav.interiors': 'Interiors',
    'nav.wellness': 'Wellness',
    'nav.plans': 'Plans',
    'nav.contact': 'Viewing',
    'nav.menu': 'Menu',
    'nav.close': 'Close',
    'hero.aria': 'Kitchen and living',
    'hero.location': 'Marbella · Spain',
    'hero.tagline': 'A quiet house between stone, light and garden.',
    'hero.cta.plans': 'View floor plans',
    'hero.cta.viewing': 'Request viewing',
    'hero.alt': 'Open kitchen and living with sheer curtains billowing by the glass doors',
    'opening.kicker': 'The residence',
    'opening.headline': 'Designed to be felt<br>before it is understood.',
    'opening.p1': 'Los Verdiales is conceived as one whole — architecture, interiors and landscape in a single movement. The rooms open towards the garden. Stone, oak, brass and linen bring warmth and permanence.',
    'opening.p2': 'The luxury is in proportion, craftsmanship and daylight. The house is deliberately calm.',
    'facts.place.label': 'Location',
    'facts.residence.label': 'Residence',
    'facts.wellness.label': 'Wellness',
    'facts.plan.label': 'Layout',
    'kitchen.kicker': 'Kitchen and living',
    'kitchen.headline': 'The house opens here.',
    'kitchen.body': 'Kitchen island, living room and garden in a single run. Sage lanterns, oak and stone — the room the day gathers in.',
    'kitchen.alt': 'Open kitchen and living with sage lanterns, sofa and glass towards the garden',
    'bedroom.kicker': 'Primary suite',
    'bedroom.headline': 'A softer rhythm.',
    'bedroom.body': 'White wingback, layered textiles and moody lamps. A room that feels lived-in — not styled.',
    'bedroom.alt': 'Primary suite with white wingback chair and moody lamps',
    'bathroom.kicker': 'Primary bath',
    'bathroom.headline': 'Sage, brass, and quiet ritual.',
    'bathroom.body': 'A freestanding tub in muted sage beside a fluted vanity in warm brass. Earth and mineral — calm, tactile, unhurried.',
    'bathroom.alt': 'Bathroom with sage tub and fluted brass vanity',
    'lounge.kicker': 'Leisure',
    'lounge.headline': 'Evenings with no reason to end.',
    'lounge.body': 'Bar, wine wall, billiards and relaxed seating. A room of its own on the lower level — still part of the same material language.',
    'lounge.alt': 'Lounge with bar, pool table and wine wall',
    'poolgym.kicker': 'Wellness',
    'poolgym.headline': 'A retreat within the residence.',
    'poolgym.body': 'Pool, gym and spa behind glass — water, light and recovery.',
    'poolgym.alt': 'Indoor pool and gym behind glass',
    'pool.aria': 'Pool at dusk',
    'pool.kicker': 'Outdoors · At dusk',
    'pool.headline': 'Evening stillness by the water.',
    'pool.body': 'The villa at dusk. Turquoise pool, lounge chairs and chevron umbrellas — evening settles over the garden.',
    'dusk.kicker': 'At dusk',
    'dusk.headline': 'The house gathers its light.',
    'dusk.body': 'From the kitchen island, the living room opens towards the terrace and fireplace. The day settles into warmth.',
    'dusk.alt': 'Dusk living room from the kitchen island towards terrace and fireplace',
    'place.kicker': 'Marbella',
    'place.headline': 'Quiet, without being far away.',
    'place.p1': 'Los Verdiales sits in a calm corner of Marbella — close to the coast, yet sheltered by garden and stone. The day can be still here; evening gathers its light inward.',
    'place.p2': 'The house is for those who want the Mediterranean near at hand without living in noise. No brochure — just a place that breathes quietly.',
    'exterior.kicker': 'Exterior',
    'exterior.headline': 'The house in its landscape.',
    'plans.kicker': 'Private material',
    'plans.headline': 'Floor plans',
    'plans.gate.body': 'Plans are shared with those considering a private viewing. Enter your email to unlock.',
    'plans.form.name': 'Name (optional)',
    'plans.form.email': 'Email',
    'plans.form.submit': 'Unlock floor plans',
    'plans.form.error': 'Something went wrong. Try again, or request a viewing below.',
    'plans.empty': 'Floor plan loading',
    'plans.tab.hovedplan': 'Main floor',
    'plans.tab.underetasje': 'Lower level',
    'plans.tab.situasjon': 'Site plan',
    'plans.caption.hovedplan': 'Kitchen, living and primary suite',
    'plans.caption.underetasje': 'Lounge, pool and gym',
    'plans.caption.situasjon': 'House in the garden',
    'plans.download': 'Download PDF',
    'plans.lightbox.close': 'Close',
    'contact.kicker': 'Private presentation',
    'contact.headline': 'Los Verdiales<br>Marbella',
    'contact.body': 'For specifications, plans and a private viewing — request the full presentation.',
    'contact.plansNote': 'Floor plans open with an email under <a href="#plans">Plans</a>.',
    'form.name': 'Name',
    'form.email': 'Email',
    'form.phone': 'Phone',
    'form.message': 'Message',
    'form.submit': 'Request presentation',
    'footer.brand': 'Los Verdiales · Marbella · Spain',
    'footer.plans': 'Floor plans',
    'footer.contact': 'Viewing',
    'footer.location': 'Marbella · Spain',
    'thanks.title': 'Thank you — Los Verdiales',
    'thanks.headline': 'Thank you for your enquiry.',
    'thanks.body': 'We will be in touch shortly with details for a private presentation and viewing.',
    'thanks.back': 'Return to the residence'
  }
};
